# Build stage
FROM denoland/deno:alpine-2.3.5 AS build
WORKDIR /app
COPY . .
USER 1000:1000
RUN deno task web:build

# Production stage with nginx
FROM nginx:alpine
WORKDIR /app
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
