# Build stage
ARG DENO_VERSION=2.4.0
FROM financy/deno-base:${DENO_VERSION} AS build

# Copy application code
COPY --chown=1000:1000 . .

ARG VITE_ENV=prod
ENV VITE_ENV=${VITE_ENV}
ENV DENO_DIR=/deno-dir
RUN mkdir -p /deno-dir && chown -R 1000:1000 /deno-dir
RUN deno task web:build

# Production stage with nginx
FROM nginxinc/nginx-unprivileged:stable-alpine
WORKDIR /app
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
COPY --from=build /app/apps/web/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
