// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $_layout from "./routes/_layout.tsx"
import * as $_middleware from "./routes/_middleware.ts"
import * as $_types from "./routes/_types.ts"
import * as $health from "./routes/health.ts"
import * as $index from "./routes/index.tsx"
import * as $profile_index from "./routes/profile/index.tsx"
import * as $ui_guide from "./routes/ui-guide.tsx"
import * as $_index from "./islands/+index.ts"
import * as $system_Auth from "./islands/system/Auth.tsx"
import * as $system_Nav from "./islands/system/Nav.tsx"
import * as $system_Shell from "./islands/system/Shell.tsx"
import * as $system_StateInit from "./islands/system/StateInit.tsx"
import * as $system_Toastr from "./islands/system/Toastr.tsx"
import * as $system_UIGuide from "./islands/system/UIGuide.tsx"
import * as $ui_Badge from "./islands/ui/Badge.tsx"
import * as $ui_CopyButton from "./islands/ui/CopyButton.tsx"
import * as $ui_Dropdown from "./islands/ui/Dropdown.tsx"
import * as $ui_OnOffButtons from "./islands/ui/OnOffButtons.tsx"
import * as $ui_PageTitle from "./islands/ui/PageTitle.tsx"
import * as $ui_Table from "./islands/ui/Table.tsx"
import * as $ui_ToggleSwitch from "./islands/ui/ToggleSwitch.tsx"
import * as $_islands_Dashboard from "./routes/(_islands)/Dashboard.tsx"
import * as $profile_islands_Profile from "./routes/profile/(_islands)/Profile.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/_types.ts": $_types,
    "./routes/health.ts": $health,
    "./routes/index.tsx": $index,
    "./routes/profile/index.tsx": $profile_index,
    "./routes/ui-guide.tsx": $ui_guide,
  },
  islands: {
    "./islands/+index.ts": $_index,
    "./islands/system/Auth.tsx": $system_Auth,
    "./islands/system/Nav.tsx": $system_Nav,
    "./islands/system/Shell.tsx": $system_Shell,
    "./islands/system/StateInit.tsx": $system_StateInit,
    "./islands/system/Toastr.tsx": $system_Toastr,
    "./islands/system/UIGuide.tsx": $system_UIGuide,
    "./islands/ui/Badge.tsx": $ui_Badge,
    "./islands/ui/CopyButton.tsx": $ui_CopyButton,
    "./islands/ui/Dropdown.tsx": $ui_Dropdown,
    "./islands/ui/OnOffButtons.tsx": $ui_OnOffButtons,
    "./islands/ui/PageTitle.tsx": $ui_PageTitle,
    "./islands/ui/Table.tsx": $ui_Table,
    "./islands/ui/ToggleSwitch.tsx": $ui_ToggleSwitch,
    "./routes/(_islands)/Dashboard.tsx": $_islands_Dashboard,
    "./routes/profile/(_islands)/Profile.tsx": $profile_islands_Profile,
  },
  baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
