// #region Time
export const DAYS_IN_MONTH = 30
export const DAYS_IN_WEEK = 7
export const MONTHS_IN_YEAR = 12
export const HOURS_IN_DAY = 24
export const MINUTES_IN_HOUR = 60
export const SECONDS_IN_MINUTE = 60
export const MILLISECONDS_IN_SECOND = 1000
export const ONE_HOUR_IN_SECONDS = MINUTES_IN_HOUR * SECONDS_IN_MINUTE
export const ONE_DAY_IN_SECONDS = HOURS_IN_DAY * ONE_HOUR_IN_SECONDS
export const ONE_WEEK_IN_SECONDS = DAYS_IN_WEEK * ONE_DAY_IN_SECONDS
export const ONE_MONTH_IN_SECONDS = DAYS_IN_MONTH * ONE_DAY_IN_SECONDS
export const ONE_YEAR_IN_SECONDS = MONTHS_IN_YEAR * ONE_MONTH_IN_SECONDS
export const ONE_MINUTE_IN_MILLISECONDS = SECONDS_IN_MINUTE *
  MILLISECONDS_IN_SECOND
export const ONE_HOUR_IN_MILLISECONDS = ONE_HOUR_IN_SECONDS *
  MILLISECONDS_IN_SECOND
export const ONE_DAY_IN_MILLISECONDS = ONE_DAY_IN_SECONDS *
  MILLISECONDS_IN_SECOND
export const ONE_WEEK_IN_MILLISECONDS = ONE_WEEK_IN_SECONDS *
  MILLISECONDS_IN_SECOND
export const ONE_MONTH_IN_MILLISECONDS = ONE_YEAR_IN_SECONDS *
  MILLISECONDS_IN_SECOND
export const ONE_YEAR_IN_MILLISECONDS = ONE_YEAR_IN_SECONDS *
  MILLISECONDS_IN_SECOND
// #endregion Time

// #region Password
export const MIN_PASSWORD_LENGTH = 12
// #endregion Password

// #region Auth
export const USER_ID_COOKIE_NAME = "user_id"
// #endregion Auth
