services:

  db:
    healthcheck:
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s
  
  minio:
    labels:
      - "traefik.docker.network=proxy"
      - 'traefik.http.routers.${PROJECT}-minio.entrypoints=websecure'
      - 'traefik.http.routers.${PROJECT}-minio.tls=true'
      - 'traefik.http.routers.${PROJECT}-minio.tls.certresolver=myresolver'

  grafana:
    labels:
      - "traefik.docker.network=proxy"
      - 'traefik.http.routers.${PROJECT}-grafana.entrypoints=websecure'
      - 'traefik.http.routers.${PROJECT}-grafana.tls=true'
      - 'traefik.http.routers.${PROJECT}-grafana.tls.certresolver=myresolver'

  api:
    environment:
      - ENV=prod
    labels:
      - "traefik.docker.network=proxy"
      - 'traefik.http.routers.${PROJECT}-api.entrypoints=websecure'
      - 'traefik.http.routers.${PROJECT}-api.tls=true'
      - 'traefik.http.routers.${PROJECT}-api.tls.certresolver=myresolver'

  web:
    build:
      dockerfile: apps/web/dockerfile.prod
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.${PROJECT}-web.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT}-web.tls=true"
      - "traefik.http.routers.${PROJECT}-web.tls.certresolver=myresolver"
