services:
  db:
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    environment:
      - ENV=dev
    healthcheck:
      interval: 3s

  web:
    environment:
      - ENV=dev
    ports:
      - 5173:5173
    build:
      dockerfile: apps/web/dockerfile.dev
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=5173"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://127.0.0.1:5173"]
      interval: 3s
