services:
  proxy:
    command:
      - '--log.level=${PROXY_LOG_LEVEL}'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.websecure.address=:443'
      - '--entrypoints.web.address=:80'
      - '--ping=true'
      - '--ping.entryPoint=ping'
      - '--entrypoints.web.http.redirections.entrypoint.to=websecure'
      - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
      - '--entrypoints.web.http.redirections.entrypoint.permanent=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge=true'
      - '--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare'
      - '--certificatesresolvers.myresolver.acme.email=${DEV_EMAIL}'
      - '--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json'
      # - '--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory'
    environment:
      - CF_API_EMAIL=${PROXY_CF_API_EMAIL}
      - CF_API_KEY=${PROXY_CF_API_KEY}
    labels:
      - 'traefik.http.routers.proxy.entrypoints=websecure'
      - 'traefik.http.routers.proxy.tls=true'
      - 'traefik.http.routers.proxy.tls.certresolver=myresolver'

  db:
    healthcheck:
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 40s
  
  minio:
    labels:
      - 'traefik.http.routers.minio.entrypoints=websecure'
      - 'traefik.http.routers.minio.tls=true'
      - 'traefik.http.routers.minio.tls.certresolver=myresolver'

  grafana:
    labels:
      - 'traefik.http.routers.grafana.entrypoints=websecure'
      - 'traefik.http.routers.grafana.tls=true'
      - 'traefik.http.routers.grafana.tls.certresolver=myresolver'

  api:
    environment:
      - ENV=prod
    labels:
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls=true'
      - 'traefik.http.routers.api.tls.certresolver=myresolver'

  web:
    build:
      dockerfile: apps/web/dockerfile.prod
    labels:
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"